version: '3.9'

services:

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - instance
    networks:
      - my-network

  instance:
    image: weather_app
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app    
    expose:
      - "5000"
    deploy:
      replicas: 2
    networks:
      - my-network

networks:
  my-network:
    


